Repository Unibo-PPS-1920/pps-19-motoScala, pull requests merged in 2020-10, with the labels that each got.

#87 add angle getter to dir
  src/main/scala/it/unibo/pps1920/motoscala/controller/Controller.scala
  src/main/scala/it/unibo/pps1920/motoscala/ecs/util/Direction.scala
  src/test/scala/it/unibo/pps1920/motoscala/ecs/util/DirectionTest.scala
Labels: point:1, type:feature

#95 draw enemies
  src/main/scala/it/unibo/pps1920/motoscala/view/screens/game/AbstractScreenControllerGame.scala
Labels: point:1, type:feature

#139 Improved coordinator
  src/main/scala/it/unibo/pps1920/motoscala/ecs/System.scala
  src/main/scala/it/unibo/pps1920/motoscala/ecs/core/ComponentManager.scala
  src/main/scala/it/unibo/pps1920/motoscala/ecs/core/Coordinator.scala
  src/main/scala/it/unibo/pps1920/motoscala/ecs/core/ECSSignature.scala
  src/main/scala/it/unibo/pps1920/motoscala/ecs/core/EntityManager.scala
  src/main/scala/it/unibo/pps1920/motoscala/ecs/core/SystemManager.scala
  src/main/scala/it/unibo/pps1920/motoscala/ecs/core/errors/ManagerError.scala
  src/main/scala/it/unibo/pps1920/motoscala/ecs/systems/AISystem.scala
  src/main/scala/it/unibo/pps1920/motoscala/ecs/systems/CollisionsSystem.scala
  src/main/scala/it/unibo/pps1920/motoscala/ecs/systems/DrawSystem.scala
  src/main/scala/it/unibo/pps1920/motoscala/ecs/systems/EndGameSystem.scala
  src/main/scala/it/unibo/pps1920/motoscala/ecs/systems/InputSystem.scala
  src/main/scala/it/unibo/pps1920/motoscala/ecs/systems/MovementSystem.scala
  src/main/scala/it/unibo/pps1920/motoscala/ecs/systems/PowerUpSystem.scala
  src/main/scala/it/unibo/pps1920/motoscala/engine/Engine.scala
  src/test/scala/it/unibo/pps1920/motoscala/ecs/core/ComponentManagerTest.scala
  src/test/scala/it/unibo/pps1920/motoscala/ecs/core/ECSSignatureTest.scala
  src/test/scala/it/unibo/pps1920/motoscala/ecs/core/EntityManagerTest.scala
  src/test/scala/it/unibo/pps1920/motoscala/ecs/core/SystemManagerTest.scala
  src/test/scala/it/unibo/pps1920/motoscala/ecs/systems/AISystemTest.scala
  src/test/scala/it/unibo/pps1920/motoscala/ecs/systems/CollisionSystemTest.scala
  src/test/scala/it/unibo/pps1920/motoscala/ecs/systems/DrawSystemTest.scala
  src/test/scala/it/unibo/pps1920/motoscala/ecs/systems/EndGameSystemTest.scala
  src/test/scala/it/unibo/pps1920/motoscala/ecs/systems/InputSystemTest.scala
  src/test/scala/it/unibo/pps1920/motoscala/ecs/systems/MovementSystemTest.scala
  src/test/scala/it/unibo/pps1920/motoscala/ecs/systems/PowerUpSystemTest.scala
Labels: point:5, type:refactor

#141 Refactor/engine
  src/main/resources/prolog/movement.pl
  src/main/scala/it/unibo/pps1920/motoscala/controller/Controller.scala
  src/main/scala/it/unibo/pps1920/motoscala/ecs/core/Coordinator.scala
  src/main/scala/it/unibo/pps1920/motoscala/ecs/systems/AISystem.scala
  src/main/scala/it/unibo/pps1920/motoscala/ecs/util/Scala2P.scala
  src/main/scala/it/unibo/pps1920/motoscala/engine/Engine.scala
Labels: type:refactor
